---
title: "question 1 secondary"
output: html_document
date: "2023-08-24"
---
```{r}
#Load libraries
library(dplyr)
library(tidyverse)
library(splitstackshape)
library(plotrix)
library(ggplot2)
library(ggpubr)

#Load data
setwd("~/Desktop")
legacydata<-readRDS("legacydata.rds")

```

```{r}
#Subset data by ecoregion
cali_ecoregion<-legacydata[legacydata$ecoregion=='cali',]
cold_ecoregion<-legacydata[legacydata$ecoregion=='cold',]
northern_ecoregion<-legacydata[legacydata$ecoregion=='northern',]
sgs_ecoregion<-legacydata[legacydata$ecoregion=='sgs',]
hot_ecoregion<-legacydata[legacydata$ecoregion=='hot',]
```

```{r}
lm_onlyPPT_coef<-list()
lm_PPTnpp_coef<-list()

lm_onlyPPT_aic<-list()
lm_PPTnpp_aic<-list()

lm_onlyPPT_rsquared<-list()
lm_PPTnpp_rsquared<-list()
```


```{r}
for(i in 1:1000)
{
  # Stratify by region and the MAP of the region #
  test.strat.northern_mixed<-stratified(northern_ecoregion, "above_below", 0.0001)
  test.strat.cold_deserts<-stratified(cold_ecoregion,"above_below", 0.0001)
  test.strat.california_annuals<-stratified(cali_ecoregion, "above_below", 0.0001)
  test.strat.shortgrass_steppe<-stratified(sgs_ecoregion, "above_below", 0.0001)
  test.strat.hot_deserts<-stratified(hot_ecoregion,"above_below", 0.0001)
  test.strat<-rbind(test.strat.northern_mixed, test.strat.cold_deserts, test.strat.california_annuals, 
                    test.strat.shortgrass_steppe, test.strat.hot_deserts)
  
lm_onlyPPT<-lm(NPPdev~PPTdev, data=test.strat)

lm_PPTnpp<-lm(NPPdev~PPTdev+lagNPPdev, data=test.strat)

# Now get and store information from the models in the lists 
  
lm_onlyPPT_coef[[i]]<-(df.coef.create(lm_onlyPPT))
lm_PPTnpp_coef[[i]]<-(df.coef.create(lm_PPTnpp))

lm_onlyPPT_aic[[i]]<-(df.aic.create(lm_onlyPPT))
lm_PPTnpp_aic[[i]]<-(df.aic.create(lm_PPTnpp))

lm_onlyPPT_rsquared[[i]]<-(df.r.squared.create(lm_onlyPPT))
lm_PPTnpp_rsquared[[i]]<-(df.r.squared.create(lm_PPTnpp))
}
```

```{r}
write_rds(lm_onlyPPT_coef,"lm_onlyPPT_coef.rds")
write_rds(lm_PPTnpp_coef,"lm_PPTnpp_coef.rds")

write_rds(lm_onlyPPT_aic,"lm_onlyPPT_aic.rds")
write_rds(lm_PPTnpp_aic,"lm_NPP_aic.rds")

write_rds(lm_onlyPPT_rsquared,"lm_onlyPPT_rsquared.rds")
write_rds(lm_PPTnpp_rsquared,"lm_PPTnpp_rsquared.rds")
```

```{r}
setwd("~/Desktop/Legacy Project")
lm_onlyPPT_aic<-readRDS("lm_onlyPPT_aic.rds")
lm_onlyPPT_rsquared<-readRDS("lm_onlyPPT_rsquared.rds")
setwd("~/Desktop/Legacy Project")
lm_PPTnpp_aic<-readRDS("lm_PPTnpp_aic.rds")
lm_PPTnpp_rsquared<-readRDS("lm_PPTnpp_rsquared.rds")

```

```{r}
#Store Coefficients from the models in the lists
onlyPPT_coefficients<-list_to_df_initial( lm_onlyPPT_coef)
onlyPPT_coefficients$model<-'onlyPPT'
onlyPPT_coefficients <- onlyPPT_coefficients %>% 
       rename("coef" = "coefficient.PPTdev")

PPTnpp_coefficients<-list_to_df_initial(lm_PPTnpp_coef)
PPTnpp_coefficients$model<-'PPTnpp'
PPTnpp_coefficients <- PPTnpp_coefficients %>% 
       rename("coef" = "coefficient.temporal")

coefficients<-rbind(onlyPPT_coefficients,PPTnpp_coefficients)

write_rds(onlyPPT_coefficients,"onlyPPT_coefficients2.rds")
write_rds(PPTnpp_coefficients,"PPTnpp_coefficients2.rds")

PPTnpp_coefficients<-readRDS("PPTnpp_coefficients2.rds")

```



```{r}
#Store AIC scores from the models in the lists
aic.onlyPPT.binded<-bind.aic(lm_onlyPPT_aic)
aic.onlyPPT.binded$model<-'onlyPPT'

aic.PPTnpp.binded<-bind.aic(lm_PPTnpp_aic)
aic.PPTnpp.binded$model<-'PPTnpp'

aic.binded<-do.call("rbind", list(aic.PPTnpp.binded,aic.onlyPPT.binded))

write_rds(aic.binded,"aic.binded2.rds")
```

```{r}
#Store R-squared values from the models in the lists
r.squared.onlyNPP.binded<-bind.r.squared(lm_onlyPPT_rsquared)
r.squared.onlyNPP.binded$model<-'onlyPPT'

r.squared.PPTnpp.binded<-bind.r.squared(lm_PPTnpp_rsquared)
r.squared.PPTnpp.binded$model<-'PPTnpp'

rsquared.binded<-do.call("rbind", list(r.squared.onlyNPP.binded,r.squared.PPTnpp.binded))
write_rds(rsquared.binded,"rsquared.binded2.rds")
```

```{r}
setwd("~/Desktop")
aic.binded<-readRDS("aic.binded2.rds")
rsquared.binded<-readRDS("rsquared.binded2.rds")
```

```{r}

map_ecoregion_temporal_means$top99<-map_ecoregion_temporal_means$mean+(2.576*map_ecoregion_temporal_means$se)
map_ecoregion_temporal_means$bottom99<-map_ecoregion_temporal_means$mean-(2.576*map_ecoregion_temporal_means$se)
```

```{r}
#calculate mean coefficients, AIC, and R-squared values
mean_coefficients<-PPTnpp_coefficients%>%
  group_by(model)%>%
  summarise_at(vars(coef),
               list(mean))
mean_coefficients

mean_aic<-aic.binded%>%
  group_by(model)%>%
  summarise_at(vars(aic),
               list(mean=mean,
                    SE=std.error))

mean_aic$top99<-mean_aic$mean+(2.576*mean_aic$SE)
mean_aic$bottom99<-mean_aic$mean-(2.576*mean_aic$SE)


mean_rsquared<-rsquared.binded%>%
  group_by(model)%>%
  summarise_at(vars(r.squared),
               list(mean=mean,
                    SE=std.error))

mean_rsquared$top99<-mean_rsquared$mean+(2.576*mean_rsquared$SE)
mean_rsquared$bottom99<-mean_rsquared$mean-(2.576*mean_rsquared$SE)


mean_aic$upperCI<-mean_aic$meanAIC+(2.576*mean_aic$SE)
mean_aic$lowerCI<-mean_aic$meanAIC-(2.576*mean_aic$SE)


```

```{r}
#create supporting figure 2
rsquaredfigure<-ggplot(mean_rsquared,aes(y=mean, x=model, fill=model))+
  ylab("Mean R-squared")+
  xlab("Model")+
  geom_errorbar(aes(x = model, ymin = mean - SE, ymax = mean + SE), 
                position = position_dodge(width = 0.9), 
                width = 0.25,  # adjust the width of the error bars
                colour = "black", 
                alpha = 0.9, 
                size = 1.3) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_bar(stat="identity", position="dodge")+
  scale_fill_manual(values = c("darkslategray3", "indianred"),
                    labels=c("only PPT","PPT and NPP"))+
  rremove("grid")+
  theme(axis.line = element_line(),
        panel.background = element_blank())+
  theme(axis.title.x =element_text(size=20),
        axis.title.y = element_text(size=20),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18))+
 theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=13), #change legend title font size
        legend.text = element_text(size=11), 
        axis.text=element_text(size=9),
        axis.title=element_text(size=13))
rsquaredfigure
```

```{r}
aicDensity<-ggplot(aic.binded, aes(aic, fill=model))+
  geom_density(data=aic.binded, aes(x=aic, fill=model, after_stat(scaled)), alpha=1)+
  scale_x_continuous(limits = c(30500, 33000))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  labs(fill = "Model") +
  scale_y_continuous(expand = c(0,0),limits = c(0,1.01))+
  ylab("Probability Density")+
  scale_fill_manual(values=c("darkcyan","indianred"),labels=c("PPT and NPP", "Only PTT"))+
  xlab("AIC Score")+
  theme(axis.title.x =element_text( size=18),
        axis.title.y = element_text(size=18),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14))+
  theme(legend.position = c(.8,.5))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=17),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), 
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))+
  theme(legend.key.size = unit(.75, 'cm'), 
        legend.title = element_text(size=14), 
        legend.text = element_text(size=12))
aicDensity
```

```{r}
rsquaredDensity<-ggplot(rsquared.binded, aes(r.squared, fill=model))+
  geom_density(data=rsquared.binded, aes(x=r.squared, fill=model, after_stat(scaled)), alpha=1)+
  scale_x_continuous(limits = c(.1, .5))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  labs(fill = "Previous-year Condition") +
  scale_y_continuous(expand = c(0,0),limits = c(0,1.01))+
  
  scale_fill_manual(values=c("darkcyan","indianred"),labels=c("PPT and NPP", "Only PTT"))+
  ylab("Probability Density")+
  xlab("R Squared Value")+
  theme(axis.title.x =element_text( size=18),
        axis.title.y = element_text(size=18),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14))+
  theme(legend.position = c(.8,.5))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=17),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), 
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))+
  theme(legend.key.size = unit(.75, 'cm'), 
        legend.title = element_text(size=14), 
        legend.text = element_text(size=12))
```

```{r}
jpeg("Supporting fig 2(density) final.jpeg",
     width=12,
     height=6,
     units="in",
     res=300)
rsquaredaicDensity<-ggarrange(aicDensity, rsquaredDensity,
          nrow=1, ncol=2,common.legend = TRUE, labels=c('(a)','(b)'), hjust=-.1,  font.label = list(size = 16))
rsquaredaicDensity
dev.off()
```


```{r}

AICfig<-ggplot(mean_aic,aes(y=mean, x=model, fill=model))+
  ylab("Mean AIC")+
  xlab("Model")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_bar(stat="identity", position="dodge")+
  scale_fill_manual(values = c("darkslategray3", "indianred"),
                    labels=c("only PPT","PPT and NPP"))+
    geom_errorbar(aes(x = model, ymin = bottom99, ymax = top99), 
                position = position_dodge(width = 0.9), 
                width = 0.25,  # adjust the width of the error bars
                colour = "black", 
                alpha = 0.9, 
                size = 1.3) + 
  rremove("grid")+
  theme(axis.line = element_line(),
        panel.background = element_blank())+
  theme(axis.title.x =element_text(size=20),
        axis.title.y = element_text(size=20),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18))+
 theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=13), #change legend title font size
        legend.text = element_text(size=11), 
        axis.text=element_text(size=9),
        axis.title=element_text(size=13))
AICfig
```

```{r}
#create supporting figure 2
jpeg("Supporting fig 2(all ecoregions) final.jpeg",
     width=14,
     height=10,
     units="in",
     res=300)
rsquaredaic2<-ggarrange(AICfig, rsquaredfigure,
          nrow=1, ncol=2,common.legend = TRUE, labels=c('(a)','(b)'),font.label = list(size = 20))
rsquaredaic2
dev.off()
```

```{r}
#Calculate 99% CI
aic.binded.wide<-reshape(aic.binded,idvar="run.id",timevar="model",direction="wide")
aic.binded.wide$diff<-aic.binded.wide$aic.onlyPPT-aic.binded.wide$aic.PPTnpp
mean<-mean(aic.binded.wide$diff)
SE<-std.error(aic.binded.wide$diff)
mean
mean+(2.576*SE)
mean-(2.576*SE)

```

```{r}
#Calculate 99% CI
rsquared.binded.wide<-reshape(rsquared.binded,idvar="run.id",timevar="model",direction="wide")
rsquared.binded.wide$diff<-rsquared.binded.wide$r.squared.onlyPPT-rsquared.binded.wide$r.squared.PPTnpp
mean<-mean(rsquared.binded.wide$diff)
SE<-std.error(rsquared.binded.wide$diff)
mean
mean+(2.576*SE)
mean-(2.576*SE)
```

