---
title: "secondary question 3"
output: html_document
date: "2023-09-05"
---
```{r}
#Load libraries
library(dplyr)
library(tidyverse)
library(splitstackshape)
library(plotrix)

#Load data
setwd("~/Desktop")
legacydata<-readRDS("legacydata.rds")
```

```{r}
#Subset data by ecoregion
cali_ecoregion<-legacydata[legacydata$ecoregion=='cali',]
cold_ecoregion<-legacydata[legacydata$ecoregion=='cold',]
northern_ecoregion<-legacydata[legacydata$ecoregion=='northern',]
sgs_ecoregion<-legacydata[legacydata$ecoregion=='sgs',]
hot_ecoregion<-legacydata[legacydata$ecoregion=='hot',]
```

```{r}
lm_map_coef<-list()
lm_currentPPT_coef<-list()
lm_herb_coef<-list()

lm_map_aic<-list()
lm_currentPPT_aic<-list()
lm_herb_aic<-list()

lm_map_rsquared<-list()
lm_currentPPT_rsquared<-list()
lm_herb_rsquared<-list()
```


```{r}
for(i in 1:1000)
{
  # Stratify by region and the MAP of the region #
  test.strat.northern_mixed<-stratified(northern_ecoregion, "above_below", 0.0001)
  test.strat.cold_deserts<-stratified(cold_ecoregion,"above_below", 0.0001)
  test.strat.california_annuals<-stratified(cali_ecoregion, "above_below", 0.0001)
  test.strat.shortgrass_steppe<-stratified(sgs_ecoregion, "above_below", 0.0001)
  test.strat.hot_deserts<-stratified(hot_ecoregion,"above_below", 0.0001)
  test.strat<-rbind(test.strat.northern_mixed, test.strat.cold_deserts, test.strat.california_annuals, 
                    test.strat.shortgrass_steppe, test.strat.hot_deserts)

lm_currentPPT<-lm(NPPdev~ecoregion+ecoregion:PPTdev+ecoregion:lagNPPdev+ecoregion:PPTdev:lagNPPdev, data=test.strat) 

lm_map<-lm(NPPdev~ecoregion+ecoregion:PPTdev+ecoregion:MAP+ecoregion:lagNPPdev+ecoregion:MAP:lagNPPdev, data=test.strat)  

lm_herb<-lm(NPPdev~ecoregion+ecoregion:PPTdev+ecoregion:fracHERB+ecoregion:lagNPPdev+ecoregion:fracHERB:lagNPPdev, data=test.strat)

# Now get and store information from the models in the lists 
lm_map_coef[[i]]<-(df.coef.create(lm_map))
lm_currentPPT_coef[[i]]<-(df.coef.create(lm_currentPPT))
lm_herb_coef[[i]]<-(df.coef.create(lm_herb))

lm_map_aic[[i]]<-(df.aic.create(lm_map))
lm_currentPPT_aic[[i]]<-(df.coef.create(lm_currentPPT))
lm_herb_aic[[i]]<-(df.aic.create(lm_herb))

lm_map_rsquared[[i]]<-(df.r.squared.create(lm_map))
lm_currentPPT_rsquared[[i]]<-(df.coef.create(lm_currentPPT))
lm_herb_rsquared[[i]]<-(df.r.squared.create(lm_herb))
}
```


```{r}
write_rds(lm_map_coef, "lm_map_coef2.rds")
write_rds(lm_currentPPT_coef, "lm_currentPPT_coef2.rds")
write_rds(lm_herb_coef, "lm_herb_coef2.rds")

write_rds(lm_map_aic, "lm_herb_aic2.rds")
write_rds(lm_currentPPT_aic, "lm_currentPPT_aic2.rds")
write_rds(lm_herb_aic, "lm_herb_aic2.rds")

write_rds(lm_map_rsquared, "lm_map_rsquared2.rds")
write_rds(lm_currentPPT_rsquared, "lm_currentPPT_rsquared2.rds")
write_rds(lm_herb_rsquared, "lm_herb_rsquared2.rds")

setwd('~/Desktop/Legacy Project')
lm_map_coef<-readRDS("lm_map_coef1.rds")
lm_herb_coef<-readRDS("lm_herb_coef1.rds")
lm_currentPPT_coef<-readRDS("lm_currentPPT_coef1.rds")
```


```{r}
map_coefficients<-list_to_df_with_ecoregion_map(lm_map_coef)

current_coefficients<-list_to_df_with_ecoregion_current(lm_currentPPT_coef)

herb_coefficients <-list_to_df_with_ecoregion_herb(lm_herb_coef)
```



```{r}
#Calculate 99% CIs
map_ecoregion_spatiotemp_means <-map_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Spatiotemporal),
                list(mean=mean,
                     se=std.error))
map_ecoregion_spatiotemp_means$top99<-map_ecoregion_spatiotemp_means$mean+(2.576*map_ecoregion_spatiotemp_means$se)
map_ecoregion_spatiotemp_means$bottom99<-map_ecoregion_spatiotemp_means$mean-(2.576*map_ecoregion_spatiotemp_means$se)

map_ecoregion_temporal_means <-map_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Temporal),
                list(mean=mean,
                     se=std.error))
map_ecoregion_temporal_means$top99<-map_ecoregion_temporal_means$mean+(2.576*map_ecoregion_temporal_means$se)
map_ecoregion_temporal_means$bottom99<-map_ecoregion_temporal_means$mean-(2.576*map_ecoregion_temporal_means$se)

current_spatiotemp_means <-current_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Spatiotemporal.current),
                list(mean=mean,
                     se=std.error))
current_spatiotemp_means$top99<-current_spatiotemp_means$mean+(2.576*current_spatiotemp_means$se)
current_spatiotemp_means$bottom99<-current_spatiotemp_means$mean-(2.576*current_spatiotemp_means$se)

current_temp_means <-current_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Temporal.current),
                list(mean=mean,
                     se=std.error))
current_temp_means$top99<-current_temp_means$mean+(2.576*current_temp_means$se)
current_temp_means$bottom99<-current_temp_means$mean-(2.576*current_temp_means$se)

herb_ecoregion_spatiotemp_means <-herb_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Spatiotemporal.herb),
                list(mean=mean,
                     se=std.error))
herb_ecoregion_spatiotemp_means$top99<-herb_ecoregion_spatiotemp_means$mean+(2.576*herb_ecoregion_spatiotemp_means$se)
herb_ecoregion_spatiotemp_means$bottom99<-herb_ecoregion_spatiotemp_means$mean-(2.576*herb_ecoregion_spatiotemp_means$se)

herb_ecoregion_temporal_means <-herb_coefficients %>%
  group_by(ecoregion) %>%
  summarise_at(vars(Temporal.herb),
                list(mean=mean,
                     se=std.error))
herb_ecoregion_temporal_means$top99<-herb_ecoregion_temporal_means$mean+(2.576*herb_ecoregion_temporal_means$se)
herb_ecoregion_temporal_means$bottom99<-herb_ecoregion_temporal_means$mean-(2.576*herb_ecoregion_temporal_means$se)

```


```{r}
#create figure 4
mapInteraction<-ggplot()+
  geom_density(data=map_coefficients, aes(x=Spatiotemporal, fill=ecoregion,after_stat(scaled)),alpha=.6)+ 
  scale_fill_manual(values=c(northern='lightblue',cali='grey',cold='gold',hot='firebrick3',sgs='green4'),
                    labels=c(northern='Northern mixed prairies',
                             cali='California annuals',cold='Cold deserts',hot='Hot deserts',sgs='Shortgrass steppe'))+
 xlab("Change in legacy effect \n per mm MAP")+
 ylab("Probability Density")+
 theme_classic() + 
  labs(fill = "Ecoregion")+
  theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=18), #change legend title font size
        legend.text = element_text(size=16))+ 
  scale_y_continuous(expand = c(0,0),limits = c(0,1.02))+
  scale_x_continuous(limits = c(-.002,.004))+
  theme(axis.title.x =element_text( size=20),
        axis.title.y = element_text(size=20),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16))+
  theme(legend.position = c(.835,.6))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=15),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))
mapInteraction


```

```{r}
#create figure 4
herbInteraction<-ggplot()+
  geom_density(data=herb_coefficients, aes(x=Spatiotemporal.herb, fill=ecoregion,after_stat(scaled)),alpha=.6)+ 
  scale_fill_manual(values=c(northern='lightblue',cali='grey',cold='gold',hot='firebrick3',sgs='green4'),
                    labels=c(northern='Northern mixed prairies',
                             cali='California annuals',cold='Cold deserts',hot='Hot deserts',sgs='Shortgrass steppe'))+
 xlab("Change in legacy effect \n per mm MAP")+
 ylab("Probability Density")+
 theme_classic() + 
  labs(fill = "Ecoregion")+
 theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=18), #change legend title font size
        legend.text = element_text(size=16))+ 
  scale_y_continuous(expand = c(0,0),limits = c(0,1.02))+
  scale_x_continuous(limits = c(-2.5,1.5))+
  theme(axis.title.x =element_text( size=20),
        axis.title.y = element_text(size=20),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=15),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))
herbInteraction
```

```{r}
#Create supporting figure 3 
jpeg("currentPPT figure.jpeg",
    width=10,
     height=7,
     units="in",
     res=300)
currentInteraction<-ggplot()+
  geom_density(data=current_coefficients, aes(x=Spatiotemporal.current, fill=ecoregion,after_stat(scaled)),alpha=.6)+
  scale_fill_manual(values=c("firebrick3","gold","grey","lightblue","green4"),
                     labels=c("Hot Deserts","Cold Deserts","California Annuals", "Northern Mixed Prairies","Shortgrass Steppe"))+
 xlab("Change in sensitivity per legacy effect")+
 ylab("Probability Density")+
 theme_classic() + 
  labs(fill = "Ecoregion")+
  theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=18), #change legend title font size
        legend.text = element_text(size=16))+ 
  scale_y_continuous(expand = c(0,0),limits = c(0,1.02))+
  scale_x_continuous(expand = c(0,0),limits = c(-.0025,.0032))+
   theme(axis.title.x =element_text( size=20),
        axis.title.y = element_text(size=20),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16))+
  theme(legend.position = c(.85,.65))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=15),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))
currentInteraction
dev.off()
```

```{r}
#create figure 4
library(ggpubr)
jpeg("2panel Interactions.jpeg",
     width=18,
     height=10,
     units="in",
     res=300)
twoInteractions<-ggarrange(mapInteraction,herbInteraction+rremove("y.text")+rremove("y.title"),
          nrow=1, ncol=2, labels=c('(a)','(b)'),common.legend = T)
twoInteractions
dev.off()
```


```{r}
#create figure 3b
jpeg("legacy effect by ecoregion_herb.jpeg",
     width=18,
     height=10,
     units="in",
     res=300)
legeffect_byEco<-ggplot()+
  geom_density(data=current_coefficients, aes(x=Temporal.current, fill=ecoregion, after_stat(scaled)), alpha=.6)+
  scale_fill_manual(values=c("firebrick3","gold","grey","lightblue","green3"),
                       labels=c("Hot Deserts","Cold Deserts","California Annuals", "Northern Mixed Prairies","Shortgrass Steppe"))+
 xlab("Effect of Previous-year NPP")+
 ylab("Probability Density")+
 theme_classic() + 
  labs(fill = "Ecoregion")+
  theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=18), #change legend title font size
        legend.text = element_text(size=16))+ 
  scale_y_continuous(expand = c(0,0),limits = c(0,1.05))+
 #scale_x_continuous(expand = c(0,0),limits = c(-2,2))+
  theme(axis.title.x =element_text( size=20),
        axis.title.y = element_text(size=20),
        axis.text.x = element_text(size=15),
        axis.text.y = element_text(size=15))+
  theme(legend.position=c(.8,.5),
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=15),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))
legeffect_byEco
dev.off()

```

