---
title: "question 1 secondary"
output: html_document
date: "2023-08-24"
---
```{r}

#Load libraries
library(dplyr)
library(tidyverse)
library(splitstackshape)
library(plotrix)
library(ggpubr)

#Load data
#Load data
setwd("~/Desktop")
legacydata<-readRDS("legacydata.rds")
```

```{r}
#Subset data by ecoregion
cali_ecoregion<-legacydata[legacydata$ecoregion=='cali',]
cold_ecoregion<-legacydata[legacydata$ecoregion=='cold',]
northern_ecoregion<-legacydata[legacydata$ecoregion=='northern',]
sgs_ecoregion<-legacydata[legacydata$ecoregion=='sgs',]
hot_ecoregion<-legacydata[legacydata$ecoregion=='hot',]
```

```{r}
#Create empty lists for each model metric
lm_PPT_coef<-list()
lm_NPP_coef<-list()
lm_TEMP_coef<-list()

lm_PPT_aic<-list()
lm_NPP_aic<-list()
lm_TEMP_aic<-list()

lm_PPT_rsquared<-list()
lm_NPP_rsquared<-list()
lm_TEMP_rsquared<-list()
```


```{r}
for(i in 1:1000)
{
  # Stratify by region and the MAP of the region #
  test.strat.northern_mixed<-stratified(northern_ecoregion, "above_below", 0.0001)
  test.strat.cold_deserts<-stratified(cold_ecoregion,"above_below", 0.0001)
  test.strat.california_annuals<-stratified(cali_ecoregion, "above_below", 0.0001)
  test.strat.shortgrass_steppe<-stratified(sgs_ecoregion, "above_below", 0.0001)
  test.strat.hot_deserts<-stratified(hot_ecoregion,"above_below", 0.0001)
  test.strat<-rbind(test.strat.northern_mixed, test.strat.cold_deserts, test.strat.california_annuals, 
                    test.strat.shortgrass_steppe, test.strat.hot_deserts)
  
lm_PPT<-lm(NPPdev~lagPPTdev, data=test.strat)

lm_NPP<-lm(NPPdev~lagNPPdev, data=test.strat)

lm_TEMP<-lm(NPPdev~lagTEMPdev, data=test.strat)
  
# Now get and store information from the models in the lists 
lm_PPT_coef[[i]]<-(df.coef.create(lm_PPT))
lm_NPP_coef[[i]]<-(df.coef.create(lm_NPP))
lm_TEMP_coef[[i]]<-(df.coef.create(lm_TEMP))

lm_PPT_aic[[i]]<-(df.aic.create(lm_PPT))
lm_NPP_aic[[i]]<-(df.aic.create(lm_NPP))
lm_TEMP_aic[[i]]<-(df.aic.create(lm_TEMP))

lm_PPT_rsquared[[i]]<-(df.r.squared.create(lm_PPT))
lm_NPP_rsquared[[i]]<-(df.r.squared.create(lm_NPP))
lm_TEMP_rsquared[[i]]<-(df.r.squared.create(lm_TEMP))
}
```


```{r}
setwd("~/Desktop/Legacy Project")
lm_PPT_coef<-readRDS("lm_PPT_coef1.rds")
lm_NPP_coef<-readRDS("lm_NPP_coef1.rds")
lm_TEmp_coef<-readRDS("lm_TEMP_coef1.rds")

lm_PPT_aic<-readRDS("lm_PPT_aic1.rds")
lm_NPP_aic<-readRDS("lm_NPP_aic1.rds")
lm_TEMP_aic<-readRDS("lm_TEMP_aic1.rds")

lm_PPT_rsquared<-readRDS("lm_PPT_rsquared1.rds")
lm_NPP_rsquared<-readRDS("lm_NPP_rsquared1.rds")
lm_TEMP_rsquared<-readRDS("lm_TEMP_rsquared1.rds")

```


```{r}

#Store Coefficients from the models in the lists
PPT_coefficients<-list_to_df_initial( lm_PPT_coef)
PPT_coefficients$model<-'PPT'
PPT_coefficients <- PPT_coefficients %>% 
       rename("coef" = "coefficient.lagPPTdev")

NPP_coefficients<-list_to_df_initial(lm_NPP_coef)
NPP_coefficients$model<-'NPP'
NPP_coefficients <- NPP_coefficients %>% 
       rename("coef" = "coefficient.temporal")

TEMP_coefficients<-list_to_df_initial(lm_TEMP_coef)
TEMP_coefficients$model<-'TEMP'
TEMP_coefficients <- TEMP_coefficients %>% 
       rename("coef" = "coefficient.lagTEMPdev")

coefficients<-rbind(NPP_coefficients,PPT_coefficients,TEMP_coefficients)
```

```{r}
#Store AIC scores from the models in the lists
aic.PPT.binded<-bind.aic(lm_PPT_aic)
aic.PPT.binded$model<-'PPT'

aic.NPP.binded<-bind.aic(lm_NPP_aic)
aic.NPP.binded$model<-'NPP'

aic.TEMP.binded<-bind.aic(lm_TEMP_aic)
aic.TEMP.binded$model<-'TEMP'

aic.binded<-do.call("rbind", list(aic.NPP.binded,aic.PPT.binded,aic.TEMP.binded))
```

```{r}
#Store R-squared values from the models in the lists
r.squared.NPP.binded<-bind.r.squared(lm_NPP_rsquared)
r.squared.NPP.binded$model<-'NPP'

r.squared.PPT.binded<-bind.r.squared(lm_PPT_rsquared)
r.squared.PPT.binded$model<-'PPT'

r.squared.TEMP.binded<-bind.r.squared(lm_TEMP_rsquared)
r.squared.TEMP.binded$model<-'TEMP'

rsquared.binded<-do.call("rbind", list(r.squared.NPP.binded,r.squared.PPT.binded,r.squared.TEMP.binded))
```

```{r}
#Calculate mean values for coefficients, aic, and r-squared values
mean_coefficients<-coefficients%>%
  group_by(model)%>%
  summarise_at(vars(coef),
               list(mean))
mean_coefficients

mean_aic<-aic.binded%>%
  group_by(model)%>%
  summarise_at(vars(aic),
               list(meanAIC=mean,
                    SE=std.error))
mean_aic

mean_rsquared<-rsquared.binded%>%
  group_by(model)%>%
  summarise_at(vars(r.squared),
               list(rsquared=mean,
                    SE=std.error))
mean_rsquared


mean_rsquared$upperCI<-mean_rsquared$rsquared+(2.576*mean_rsquared$SE)
mean_rsquared$lowerCI<-mean_rsquared$rsquared-(2.576*mean_rsquared$SE)


mean_aic$upperCI<-mean_aic$meanAIC+(2.576*mean_aic$SE)
mean_aic$lowerCI<-mean_aic$meanAIC-(2.576*mean_aic$SE)

```


```{r}
max(aic.binded$aic)
aicDensity<-ggplot(aic.binded, aes(aic, fill=model))+
  geom_density(data=aic.binded, aes(x=aic, fill=model, after_stat(scaled)), alpha=.5)+
  scale_x_continuous(limits = c(31700, 34000))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  
  scale_fill_manual(values = c("dodgerblue2", "darkolivegreen3","orangered2"), labels = c("NPP","PPT","TEMP"))+
  labs(fill = "Previous-year Condition") +
  scale_y_continuous(expand = c(0,0),limits = c(0,1.01))+
  ylab("Probability Density")+
  xlab("AIC Score")+
  theme(axis.title.x =element_text( size=18),
        axis.title.y = element_text(size=18),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14))+
  theme(legend.position = c(.8,.5))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=17),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), 
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))+
  theme(legend.key.size = unit(.75, 'cm'), 
        legend.title = element_text(size=14), 
        legend.text = element_text(size=12))
aicDensity
```

```{r}
rsquaredDensity<-ggplot(rsquared.binded, aes(r.squared, fill=model))+
  geom_density(data=rsquared.binded, aes(x=r.squared, fill=model, after_stat(scaled)), alpha=.6)+
  scale_x_continuous(limits = c(-.01, .3))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  
  scale_fill_manual(values = c("dodgerblue2", "darkolivegreen3","orangered2"), labels = c("NPP","PPT","TEMP"))+
  labs(fill = "Previous-year Condition") +
  scale_y_continuous(expand = c(0,0),limits = c(0,1.01))+
  ylab("Probability Density")+
  xlab("R Squared Value")+
  theme(axis.title.x =element_text( size=18),
        axis.title.y = element_text(size=18),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14))+
  theme(legend.position = c(.8,.5))+
  theme(
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=17),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), 
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"))+
  theme(legend.key.size = unit(.75, 'cm'), 
        legend.title = element_text(size=14), 
        legend.text = element_text(size=12))
rsquaredDensity
```

```{r}
jpeg("Supporting fig 1(density) final.jpeg",
     width=12,
     height=6,
     units="in",
     res=300)
rsquaredaicDensity<-ggarrange(aicDensity, rsquaredDensity,
          nrow=1, ncol=2,common.legend = TRUE, labels=c('(a)','(b)'), hjust=-.1,  font.label = list(size = 16))
rsquaredaicDensity
dev.off()
```

```{r}
#create supporting figure 1 
rsquaredfigure<-ggplot(mean_rsquared,aes(y=rsquared, x=model, fill=model))+
  ylab("Mean R-squared")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_errorbar(aes(ymin = rsquared - SE, ymax = rsquared + SE), color = "black",width=.4) +
  geom_bar(stat="identity", position="dodge")+
  scale_fill_manual(values = c("darkslategray3", "indianred","purple3"))+
  rremove("grid")+
  theme(axis.line = element_line(),
        panel.background = element_blank())+
  theme(axis.title.x =element_text(size=20),
        axis.title.y = element_text(size=20),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18))+
 theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=13), #change legend title font size
        legend.text = element_text(size=11), 
        axis.text=element_text(size=9),
        axis.title=element_text(size=13))
rsquaredfigure
```

```{r}
#create supporting fig
AICfig<-ggplot(mean_aic,aes(y=aic, x=model, fill=model))+
  ylab("Mean AIC")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  geom_bar(stat="identity", position="dodge")+
  scale_fill_manual(values = c("darkslategray3", "indianred","purple3"))+
  rremove("grid")+
  theme(axis.line = element_line(),
        panel.background = element_blank())+
  theme(axis.title.x =element_text(size=20),
        axis.title.y = element_text(size=20),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18))+
 theme(legend.key.size = unit(.75, 'cm'), #change legend key size
        legend.title = element_text(size=13), #change legend title font size
        legend.text = element_text(size=11), 
        axis.text=element_text(size=9),
        axis.title=element_text(size=13))
AICfig
```

```{r}
#create supporting fi 1 
jpeg("Supporting fig 1(all ecoregion).jpeg",
     width=12,
     height=14,
     units="in",
     res=300)
rsquaredaic<-ggarrange(AICfig + rremove("xlab")+rremove("x.text"), rsquaredfigure,
          nrow=2, ncol=1,common.legend = TRUE)
rsquaredaic
dev.off()
```


```{r}
#calculate 99% CIs 
aic.binded.wide<-reshape(aic.binded,idvar="run.id",timevar="model",direction="wide")
aic.binded.wide$PPTdiff<-aic.binded.wide$aic.PPT-aic.binded.wide$aic.NPP
aic.binded.wide$TEMPdiff<-aic.binded.wide$aic.TEMP-aic.binded.wide$aic.NPP
meanPPT<-mean(aic.binded.wide$PPTdiff)
SEPPT<-std.error(aic.binded.wide$PPTdiff)
meanPPT
meanPPT+(2.576*SEPPT)
meanPPT-(2.576*SEPPT)

meanTEMP<-mean(aic.binded.wide$TEMPdiff)
SETEMP<-std.error(aic.binded.wide$TEMPdiff)
meanTEMP
meanTEMP+(2.576*SETEMP)
meanTEMP-(2.576*SETEMP)

 z_score <- qnorm(0.995) 
```

```{r}
#calculate 99% CIs 
rsquared.binded.wide<-reshape(rsquared.binded,idvar="run.id",timevar="model",direction="wide")
rsquared.binded.wide$PPTdiff<-rsquared.binded.wide$r.squared.PPT-rsquared.binded.wide$r.squared.NPP
rsquared.binded.wide$TEMPdiff<-rsquared.binded.wide$r.squared.TEMP-rsquared.binded.wide$r.squared.NPP
meanPPT<-mean(rsquared.binded.wide$PPTdiff)
SEPPT<-std.error(rsquared.binded.wide$PPTdiff)
meanPPT
meanPPT+(2.576*SEPPT)
meanPPT-(2.576*SEPPT)

meanTEMP<-mean(rsquared.binded.wide$TEMPdiff)
SETEMP<-std.error(rsquared.binded.wide$TEMPdiff)
meanTEMP
meanTEMP+(2.576*SETEMP)
meanTEMP-(2.576*SETEMP)

```

