---
title: "map for paper"
output: html_document
date: "2023-05-10"
---

```{r}
#Load libraries
library(dplyr)
library(tidyverse)
library(raster)
library(rgdal)
library(graphics)
library(ggpubr)
library(scico)
library(ggpubr)

setwd("~/Desktop")
legacydata<-readRDS("legacydata.rds")

cali_ecoregion<-legacydata[legacydata$ecoregion=='cali',]
cold_ecoregion<-legacydata[legacydata$ecoregion=='cold',]
northern_ecoregion<-legacydata[legacydata$ecoregion=='northern',]
sgs_ecoregion<-legacydata[legacydata$ecoregion=='sgs',]
hot_ecoregion<-legacydata[legacydata$ecoregion=='hot',]

#Run per pixel model on equation 4 and extract coefficients to map
mlrmodel<-legacydata%>%
  group_by(x,y)%>%
  do(model=lm(NPPdev~PPTdev+lagNPPdev, data=.))%>%
  mutate(coef=coef(model)[3])


mlrmodel <- mlrmodel %>%
  select(x, y, coef)


#Export data
write_rds(mlrmodel, "perpixelmodel_final.rds")



```

```{r}
setwd("~/Desktop")
mlrmodel<-readRDS("perpixelmodel_final.rds")
#Subset data to middle 95% in order to better show variability
quantile(mlrmodel$coef,probs=c(0.025,0.975))
mlrmodelsubset<-mlrmodel[mlrmodel$coef>-0.001712205 & mlrmodel$coef<0.796500417, ] 
```
```{r}
merged<-merge(legacydata,mlrmodel,by=c("x","y"))

merged<-merged%>%
  group_by(x,y)%>%
  mutate(NPPsd=sd(NPP))

merged<-merged%>%
  group_by(x,y)%>%
  mutate(mean=mean(NPP))

merged<-merged%>%
  group_by(x,y)%>%
  mutate(cv=NPPsd/mean)

```

```{r}
ggplot(data=merged,aes(x=cv, y=coef))+
  geom_point()+
  facet_wrap(~ecoregion)

```

```{r}
#Transform data from df to raster
r_obj <- raster(xmn=-122.9, xmx=-97, ymn=28, ymx=49, resolution=c(0.01347473, 0.01347473))

mlrcoefsubset<- rasterize(x=mlrmodelsubset[, 1:2], # lon-lat data
                    y=r_obj, # raster object
                    field=mlrmodelsubset[,3 ], # vals to fill raster with
                    fun=mean) # aggregate function
```

```{r}
#Create states outline data
setwd("~/Desktop/rds")
us<-readRDS("gadm36_USA_1_sp.rds")
us<-getData("GADM", country='USA', level=1,download=TRUE)
states_all_sites <- us[us$NAME_1 %in% c('California','New Mexico','Arizona','Utah',
                                        'Arizona','Colorado','Washington','Wyoming',
                                        'Idaho','Oregon','Idaho','Montana','Texas',
                                        'North Dakota','South Dakota','Nebraska',
                                        'Oklahoma','Kansas'),]

aea.proj <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
states_all_sites <- spTransform(states_all_sites, CRS(aea.proj))
```



```{r}
#Change projection
proj4string(mlrcoefsubset) <- CRS("+proj=longlat")
mlrcoefsubset2<-projectRaster(mlrcoefsubset, crs=aea.proj)
mlrcoefsubsetdf<-rasterToPoints(mlrcoefsubset2)
mlrcoefsubsetdf<-as.data.frame(mlrcoefsubsetdf)
```


```{r}
#Create map
map<-ggplot() + 
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
               color = "black", linewidth = 0.1,fill=NA)+
  geom_raster(data=mlrcoefsubsetdf, mapping=aes(x = x, y = y, fill = layer)) + 
  coord_equal() +
  theme_classic()+
  scale_fill_scico(palette = "roma",direction=-1.)+
  xlab('') +
  ylab('') +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
  scale_colour_gradient(
                        breaks = c(.2, .4, .6),
                        labels = c(.2, .4, .6))+
    theme(legend.title = element_text(size=20), #change legend title font size
        legend.text = element_text(size=14),
        legend.direction="horizontal",
        legend.position = "top")+
  guides(fill=guide_colourbar(barwidth=12, barheight=1, title.hjust=0, title="Legacy Effect ", draw.llim = TRUE, draw.ulim = TRUE,))
map

dev.off()
```

```{r}
jpeg("map and density.jpeg",
     width=16,
     height=6,
     units="in",
     res=300)
ggarrange(map,legeffect_byEco,labels=c('(a)','(b)'))
dev.off()
```



