---
title: "importing data"
output: html_document
date: "2023-07-26"
---
```{r}
#Load libraries
library(raster)
library(stringr)
library(dplyr)
library(tidyverse)
```

```{r}
setwd("~/Desktop/Legacy Project/cali annuals/npp geotifs for CALI annuals") #Set working directory for California annuals geotifs
raster1986cali<-stack("1986nppCALI.tif")#Stack a raster file for 1986 so that we have all 4 bands (afgNPP, pfgNPP, shrNPP, treNPP), to be later used to resample data to this extent

#Create a filepath to all the NPP geotif files. 
filepathNPPcali<-file.path("~/Desktop/Legacy Project/cali annuals/npp geotifs for CALI annuals")

#Create a directory with full names for all the NPP geotiff files. 
dirNPPcali<-dir(filepathNPPcali, full.names = T)

#Create a loop that creates a rasterstack, converts the rasterstack data to points, creates a data frame from the point data, adds together the afg, pfg, shr, and tre NPP into one total NPP creates a year variable with characters 50-53 from the file name, and rounds the decimal points to four. This loop will do this process for all files in the NPP geotiff directory. 
nppcali<-lapply(dirNPPcali,function(dirNPPcali){ 
  rasters<-stack(dirNPPcali)
  rasterdata<-rasterToPoints(rasters)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$NPP <- as.numeric(apply(rasterdf[,3:6],1,sum))
  rasterdf$year<-(as.character(dirNPPcali))
  rasterdf$year<-substr(rasterdf$year, 82,85)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

nppdfcali<-bind_rows(nppcali) #Bind all rows together

#Repeat this loop for PPT and Herbaceous cover geotif files 

filepathPPTcali<-file.path("~/Desktop/Legacy Project/cali annuals/prcp geotifs CALI")
dirPPTcali<-dir(filepathPPTcali, full.names = T)

pptcali<-lapply(dirPPTcali,function(dirPPTcali){ 
  rastersprcp<-stack(dirPPTcali)
  resampled<-resample(rastersprcp,raster1986cali)
  rasterdataprcp<-rasterToPoints(resampled)
  rasterdfprcp<-as.data.frame(rasterdataprcp)
  rasterdfprcp$year<-(as.character(dirPPTcali))
  rasterdfprcp$year<-substr(rasterdfprcp$year, 71,74)
  rasterdfprcp <- rasterdfprcp%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdfprcp)
  })

pptdfcali<-bind_rows(pptcali) 

filepathTEMPcali<-file.path("~/Desktop/Legacy Project/cali annuals/cali temp")
dirTEMPcali<-dir(filepathTEMPcali, full.names = T)

tempcali<-lapply(dirTEMPcali,function(dirTEMPcali){ 
  rasters<-stack(dirTEMPcali)
  resampled<-resample(rasters,raster1986cali)
  rasterdata<-rasterToPoints(resampled)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf<-subset(rasterdf,select=-c(dayl,prcp,srad,swe,tmin,tmax,vp))
  rasterdf$year<-(as.character(dirTEMPcali))
  rasterdf$year<-substr(rasterdf$year, 63,66)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

tempdfcali<-bind_rows(tempcali)

#Left join the NPP dataframe, and the PPT dataframe, by x, y and year.
CALIdata <- pptdfcali %>% 
  left_join(nppdfcali, by = c("x", "y", "year"))%>% 
  left_join(tempdfcali, by = c("x", "y", "year"))

CALIdata$ecoregion<-"cali"

#rename precipitation variable 
CALIdata<-CALIdata%>%
  rename("PPT"="prcp")


#Correct NPP units 
CALIdata <- CALIdata %>%
  mutate_at(vars(afgNPP, pfgNPP, shrNPP, treNPP, NPP), ~ . * 0.1)

#Create a unique ID for each pixel
CALIdata <-transform(CALIdata,ID=as.numeric((interaction(x,y, drop=TRUE))))

CALIdata<-CALIdata%>%
  group_by(ID)%>%
  filter(!any(is.na(NPP)))%>%
  filter(!any(NPP<10))

CALIdata <- CALIdata %>%
  group_by(ID) %>%
  mutate(pue = mean(NPP) / mean(PPT))

CALIdata<-CALIdata%>%
  group_by(ecoregion)%>%
  mutate(
    meanPUE = mean(pue, na.rm = TRUE),
    PUEsd = sd(pue, na.rm = TRUE))


#Calculate the min and max PUE values we want (+/- 3 standard deviations from the mean)
CALIdata <- within(CALIdata, {
  maxPUE <- meanPUE + 3 * PUEsd
  minPUE <- meanPUE - 3 * PUEsd
})

#Group the data by ID and remove any group that has any PUE value that is greater than or less than 3 SDs from the mean. 
CALIdata<-CALIdata%>%
  group_by(ID)%>%
  filter(!any(pue<minPUE))%>%
  filter(!any(pue>maxPUE))

#Create a logged variable for both PPT and NPP. Lag by 282447 observations(number of observations/pixel per year) so that the lagged variables are exactly 1 year behind 
CALIdata$lagPPT<-as.numeric(lag(CALIdata$PPT, 35893))
CALIdata$lagNPP<-as.numeric(lag(CALIdata$NPP, 35893))
CALIdata$lagTEMP<-as.numeric(lag(CALIdata$temp, 35893))
CALIdata<-na.omit(CALIdata)

write_rds(CALIdata, "CALIdata2.rds" )

#Remove unnecessary datasets to clear up space in global environement
rm(nppcali,nppdfcali,pptcali,pptdfcali,raster1986cali,tempcali,tempdfcali)
```

#Repeat the previous loop for all ecoregions. 
```{r}
setwd("~/Desktop/Legacy Project/cold deserts/cold deserts npp") #Set working directory for COLD annuals geotifs
raster1986cold<-stack("1986nppcold.tif")

filepathNPPcold<-file.path("~/Desktop/Legacy Project/cold deserts/cold deserts npp")

dirNPPcold<-dir(filepathNPPcold, full.names = T)

nppcold<-lapply(dirNPPcold,function(dirNPPcold){ 
  rasters<-stack(dirNPPcold)
  rasterdata<-rasterToPoints(rasters)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$NPP <- as.numeric(apply(rasterdf[,3:6],1,sum))
  rasterdf$year<-(as.character(dirNPPcold))
  rasterdf$year<-substr(rasterdf$year, 70,73)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

nppdfcold<-bind_rows(nppcold)

filepathPPTcold<-file.path("~/Desktop/Legacy Project/cold deserts/cold deserts prcp")
dirPPTcold<-dir(filepathPPTcold, full.names = T)

pptcold<-lapply(dirPPTcold,function(dirPPTcold){ 
  rastersprcp<-stack(dirPPTcold)
  resampled<-resample(rastersprcp,raster1986cold)
  rasterdataprcp<-rasterToPoints(resampled)
  rasterdfprcp<-as.data.frame(rasterdataprcp)
  rasterdfprcp$year<-(as.character(dirPPTcold))
  rasterdfprcp$year<-substr(rasterdfprcp$year, 71,74)
  rasterdfprcp <- rasterdfprcp%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdfprcp)
  })

pptdfcold<-bind_rows(pptcold) 

filepathTEMPcold<-file.path("~/Desktop/Legacy Project/cold deserts/cold temp")
dirTEMPcold<-dir(filepathTEMPcold, full.names = T)

tempcold<-lapply(dirTEMPcold,function(dirTEMPcold){ 
  rasters<-stack(dirTEMPcold)
  resampled<-resample(rasters,raster1986cold)
  rasterdata<-rasterToPoints(resampled)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf<-subset(rasterdf,select=-c(dayl,prcp,srad,swe,tmin,tmax,vp))
  rasterdf$year<-(as.character(dirTEMPcold))
  rasterdf$year<-substr(rasterdf$year, 63,66)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

tempdfcold<-bind_rows(tempcold)


COLDdata<-left_join(pptdfcold,nppdfcold, by=c("x","y","year"))
COLDdata<-left_join(COLDdata,tempdfcold,by=c("x","y","year"))

COLDdata$ecoregion<-"cold"

COLDdata<-COLDdata%>%
  rename("PPT"="prcp")

COLDdata <- COLDdata %>%
  mutate_at(vars(afgNPP, pfgNPP, shrNPP, treNPP, NPP), ~ . * 0.1)

COLDdata <-transform(COLDdata,ID=as.numeric((interaction(x,y, drop=TRUE))))

COLDdata<-COLDdata%>%
  group_by(ID)%>%
  filter(!any(is.na(NPP)))%>%
  filter(!any(NPP<10))

COLDdata <- COLDdata %>%
  group_by(ID) %>%
  mutate(pue = mean(NPP) / mean(PPT)) %>%
  group_by(ecoregion) %>%
  mutate(
    meanPUE = mean(pue, na.rm = TRUE),
    PUEsd = sd(pue, na.rm = TRUE)
  )

COLDdata <- within(COLDdata, {
  maxPUE <- meanPUE + 3 * PUEsd
  minPUE <- meanPUE - 3 * PUEsd
})

COLDdata<-COLDdata%>%
  group_by(ID)%>%
  filter(!any(pue<minPUE))%>%
  filter(!any(pue>maxPUE))

COLDdata$lagPPT<-as.numeric(lag(COLDdata$PPT, 324650))
COLDdata$lagNPP<-as.numeric(lag(COLDdata$NPP, 324650))
COLDdata$lagTEMP<-as.numeric(lag(COLDdata$temp, 324650))
COLDdata<-na.omit(COLDdata)

write_rds(COLDdata, "COLDdata2.rds" )
rm(nppcold,nppdfcold,pptcold,pptdfcold,raster1986cold,tempcold,tempdfcold)
```

```{r}
setwd('~/Desktop/Legacy Project/ns/geotiffs NS ') #Set working directory for ns annuals geotifs
raster1986ns<-stack("1986npp.tif")

filepathNPPns<-file.path('~/Desktop/Legacy Project/ns/geotiffs NS ') 

dirNPPns<-dir(filepathNPPns, full.names = T)

nppns<-lapply(dirNPPns,function(dirNPPns){ 
  rasters<-stack(dirNPPns)
  rasterdata<-rasterToPoints(rasters)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$NPP <- as.numeric(apply(rasterdf[,3:6],1,sum))
  rasterdf$year<-(as.character(dirNPPns))
  rasterdf$year<-substr(rasterdf$year, 56,59)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

nppdfns<-bind_rows(nppns)

filepathPPTns<-file.path("~/Desktop/Legacy Project/ns/prcp geotifs NS")
dirPPTns<-dir(filepathPPTns, full.names = T)

pptns<-lapply(dirPPTns,function(dirPPTns){ 
  rastersprcp<-stack(dirPPTns)
  resampled<-resample(rastersprcp,raster1986ns)
  rasterdataprcp<-rasterToPoints(resampled)
  rasterdfprcp<-as.data.frame(rasterdataprcp)
  rasterdfprcp$year<-(as.character(dirPPTns))
  rasterdfprcp$year<-substr(rasterdfprcp$year, 63,66)
  rasterdfprcp <- rasterdfprcp%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdfprcp)
  })

pptdfns<-bind_rows(pptns) 

filepathTEMPns<-file.path("~/Desktop/Legacy Project/ns/ns temp")
dirTEMPns<-dir(filepathTEMPns, full.names = T)

tempns<-lapply(dirTEMPns,function(dirTEMPns){ 
  rasters<-stack(dirTEMPns)
  resampled<-resample(rasters,raster1986ns)
  rasterdata<-rasterToPoints(resampled)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf<-subset(rasterdf,select=-c(dayl,prcp,srad,swe,tmin,tmax,vp))
  rasterdf$year<-(as.character(dirTEMPns))
  rasterdf$year<-substr(rasterdf$year, 51,54)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

tempdfns<-bind_rows(tempns)

NSdata<-left_join(pptdfns,nppdfns, by=c("x","y","year"))
NSdata<-left_join(NSdata,tempdfns,by=c("x", "y", "year"))

NSdata<-NSdata%>%
  rename("PPT"="prcp")

NSdata$ecoregion<-"northern"

#Correct NPP units 
NSdata <- NSdata %>%
  mutate_at(vars(afgNPP, pfgNPP, shrNPP, treNPP, NPP), ~ . * 0.1)

#Create a unique ID for each pixel
NSdata <-transform(NSdata,ID=as.numeric((interaction(x,y, drop=TRUE))))

NSdata<-NSdata%>%
  group_by(ID)%>%
  filter(!any(is.na(NPP)))%>%
  filter(!any(NPP<10))

NSdata <- NSdata %>%
  group_by(ID) %>%
  mutate(pue = mean(NPP) / mean(PPT)) %>%
  group_by(ecoregion) %>%
  mutate(
    meanPUE = mean(pue, na.rm = TRUE),
    PUEsd = sd(pue, na.rm = TRUE)
  )

NSdata <- within(NSdata, {
  maxPUE <- meanPUE + 3 * PUEsd
  minPUE <- meanPUE - 3 * PUEsd
})

NSdata<-NSdata%>%
  group_by(ID)%>%
  filter(!any(pue<minPUE))%>%
  filter(!any(pue>maxPUE))

NSdata$lagPPT<-as.numeric(lag(NSdata$PPT, 312381))
NSdata$lagNPP<-as.numeric(lag(NSdata$NPP, 312381))
NSdata$lagTEMP<-as.numeric(lag(NSdata$temp, 312381))
NSdata<-na.omit(NSdata)

write_rds(NSdata, "NSdata2.rds" )
rm(nppns,nppdfns,pptns,pptdfns,raster1986ns,tempns,tempdfns)
```

```{r}
setwd("~/Desktop/Legacy Project/sgs/SGS npp") #Set working directory for ns annuals geotifs
raster1986sgs<-stack("1986nppSGS.tif")

filepathNPPsgs<-file.path('~/Desktop/Legacy Project/sgs/SGS npp')

dirNPPsgs<-dir(filepathNPPsgs, full.names = T)

nppsgs<-lapply(dirNPPsgs,function(dirNPPsgs){ 
  rasters<-stack(dirNPPsgs)
  rasterdata<-rasterToPoints(rasters)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$NPP <- as.numeric(apply(rasterdf[,3:6],1,sum))
  rasterdf$year<-(as.character(dirNPPsgs))
  rasterdf$year<-substr(rasterdf$year, 52,55)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

nppdfsgs<-bind_rows(nppsgs)

filepathPPTsgs<-file.path("~/Desktop/Legacy Project/sgs/SGS prcp")
dirPPTsgs<-dir(filepathPPTsgs, full.names = T)

pptsgs<-lapply(dirPPTsgs,function(dirPPTsgs){ 
  rastersprcp<-stack(dirPPTsgs)
  resampled<-resample(rastersprcp,raster1986sgs)
  rasterdataprcp<-rasterToPoints(resampled)
  rasterdfprcp<-as.data.frame(rasterdataprcp)
  rasterdfprcp$year<-(as.character(dirPPTsgs))
  rasterdfprcp$year<-substr(rasterdfprcp$year, 53,56)
  rasterdfprcp <- rasterdfprcp%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdfprcp)
  })

pptdfsgs<-bind_rows(pptsgs) 

filepathTEMPsgs<-file.path("~/Desktop/Legacy Project/sgs/sgs temp")
dirTEMPsgs<-dir(filepathTEMPsgs, full.names = T)

tempsgs<-lapply(dirTEMPsgs,function(dirTEMPsgs){ 
  rasters<-stack(dirTEMPsgs)
  resampled<-resample(rasters,raster1986sgs)
  rasterdata<-rasterToPoints(resampled)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf<-subset(rasterdf,select=-c(dayl,prcp,srad,swe,tmin,tmax,vp))
  rasterdf$year<-(as.character(dirTEMPsgs))
  rasterdf$year<-substr(rasterdf$year, 53,56)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

tempdfsgs<-bind_rows(tempsgs)

SGSdata<-left_join(pptdfsgs,nppdfsgs, by=c("x","y","year"))
SGSdata<-left_join(SGSdata,tempdfsgs, by=c("x","y","year"))

SGSdata<-SGSdata%>%
  rename("PPT"="prcp")

SGSdata$ecoregion<-"sgs"

SGSdata <- SGSdata %>%
  mutate_at(vars(afgNPP, pfgNPP, shrNPP, treNPP, NPP), ~ . * 0.1)

SGSdata <-transform(SGSdata,ID=as.numeric((interaction(x,y, drop=TRUE))))

SGSdata<-SGSdata%>%
  group_by(ID)%>%
  filter(!any(is.na(NPP)))%>%
  filter(!any(NPP<10))

SGSdata <- SGSdata %>%
  group_by(ID) %>%
  mutate(pue = mean(NPP) / mean(PPT)) %>%
  group_by(ecoregion) %>%
  mutate(
    meanPUE = mean(pue, na.rm = TRUE),
    PUEsd = sd(pue, na.rm = TRUE)
  )

SGSdata <- within(SGSdata, {
  maxPUE <- meanPUE + 3 * PUEsd
  minPUE <- meanPUE - 3 * PUEsd
})

SGSdata<-SGSdata%>%
  group_by(ID)%>%
  filter(!any(pue<minPUE))%>%
  filter(!any(pue>maxPUE))

SGSdata$lagPPT<-as.numeric(lag(SGSdata$PPT, 122277))
SGSdata$lagNPP<-as.numeric(lag(SGSdata$NPP, 122277))
SGSdata$lagTEMP<-as.numeric(lag(SGSdata$temp, 122277))
SGSdata<-na.omit(SGSdata)

write_rds(SGSdata, "SGSdata2.rds" )


rm(nppsgs,nppdfsgs,pptsgs,pptdfsgs,raster1986sgs, tempsgs,tempdfsgs)
```

```{r}
library(raster)
library(dplyr)
setwd("~/Desktop/Legacy Project/Hot deserts/hot deserts NPP") #Set working directory for ns annuals geotifs
raster1986hot<-stack("1986nppHOT.tif")

filepathNPPhot<-file.path('~/Desktop/Legacy Project/hot deserts/hot deserts NPP')

dirNPPhot<-dir(filepathNPPhot, full.names = T)

npphot<-lapply(dirNPPhot,function(dirNPPhot){ 
  rasters<-stack(dirNPPhot)
  rasterdata<-rasterToPoints(rasters)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$NPP <- as.numeric(apply(rasterdf[,3:6],1,sum))
  rasterdf$year<-(as.character(dirNPPhot))
  rasterdf$year<-substr(rasterdf$year, 68,71)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

nppdfhot<-bind_rows(npphot)

filepathPPThot<-file.path("~/Desktop/Legacy Project/Hot deserts/hot deserts PRCP")
dirPPThot<-dir(filepathPPThot, full.names = T)

ppthot<-lapply(dirPPThot,function(dirPPThot){ 
  rastersprcp<-stack(dirPPThot)
  resampled<-resample(rastersprcp,raster1986hot)
  rasterdataprcp<-rasterToPoints(resampled)
  rasterdfprcp<-as.data.frame(rasterdataprcp)
  rasterdfprcp$year<-(as.character(dirPPThot))
  rasterdfprcp$year<-substr(rasterdfprcp$year, 69,72)
  rasterdfprcp <- rasterdfprcp%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdfprcp)
  })

pptdfhot<-bind_rows(ppthot) 

filepathHERBhot<-file.path("~/Desktop/Legacy Project/Hot deserts/hot deserts herb")
dirHERBhot<-dir(filepathHERBhot, full.names = T)

temphot<-lapply(dirTEMPhot,function(dirTEMPhot){ 
  rasters<-stack(dirTEMPhot)
  resampled<-resample(rasters,raster1986hot)
  rasterdata<-rasterToPoints(resampled)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf<-subset(rasterdf,select=-c(dayl,prcp,srad,swe,tmin,tmax,vp))
  rasterdf$year<-(as.character(dirTEMPhot))
  rasterdf$year<-substr(rasterdf$year, 61,64)
  rasterdf <- rasterdf%>%mutate_if(is.numeric, round, digits = 4)
  (rasterdf)
  })

tempdfhot<-bind_rows(temphot)

HOTdata<-left_join(pptdfhot,nppdfhot, by=c("x","y","year"))
HOTdata<-left_join(HOTdata, tempdfhot, by=c("x","y","year"))

HOTdata<-HOTdata%>%
  rename("PPT"="prcp")

HOTdata$ecoregion<-"hot"

HOTdata <- HOTdata %>%
  mutate_at(vars(afgNPP, pfgNPP, shrNPP, treNPP, NPP), ~ . * 0.1)

HOTdata <-transform(HOTdata,ID=as.numeric((interaction(x,y, drop=TRUE))))

HOTdata<-HOTdata%>%
  group_by(ID)%>%
  filter(!any(is.na(NPP)))%>%
  filter(!any(NPP<10))

HOTdata <- HOTdata %>%
  group_by(ID) %>%
  mutate(pue = mean(NPP) / mean(PPT)) %>%
  group_by(ecoregion) %>%
  mutate(
    meanPUE = mean(pue, na.rm = TRUE),
    PUEsd = sd(pue, na.rm = TRUE)
  )

HOTdata <- within(HOTdata, {
  maxPUE <- meanPUE + 3 * PUEsd
  minPUE <- meanPUE - 3 * PUEsd
})

HOTdata<-HOTdata%>%
  group_by(ID)%>%
  filter(!any(pue<minPUE))%>%
  filter(!any(pue>maxPUE))

HOTdata$lagPPT<-as.numeric(lag(HOTdata$PPT, 143668))
HOTdata$lagNPP<-as.numeric(lag(HOTdata$NPP, 143668))
HOTdata$lagTEMP<-as.numeric(lag(HOTdata$temp, 143668))
HOTdata<-na.omit(HOTdata)

write_rds(HOTdata, "HOTdata2.rds" )

rm(npphot,nppdfhot,ppthot,pptdfhot,raster1986hot)
```

```{r}
rm(CALIdata)
#Combine all ecoregion datasets to make one big dataset 
legacydata<-rbind(CALIdata,COLDdata,HOTdata,NSdata,SGSdata)

#create columns for pixel specific mean NPP,PPT,TEMP
legacydata<-legacydata%>%
  group_by(x,y,ecoregion)%>%
  mutate(NPPpixmean=mean(NPP),
         PPTpixmean=mean(PPT),
         TEMPpixmean=mean(temp))

#columns for deviations from the pixel mean for NPP, PPT, TEMP and the lagged versions of those columns
legacydata<-legacydata%>%
  group_by(x,y,ecoregion)%>%
  mutate(
    NPPdev = NPP - NPPpixmean,
    lagNPPdev = lagNPP - NPPpixmean,
    PPTdev = PPT - PPTpixmean,
    lagPPTdev = lagPPT - PPTpixmean,
    TEMPdev = temp-TEMPpixmean,
    lagTEMPdev = lagTEMP - TEMPpixmean)
    
#remove unneeded columns
legacydata<-legacydata%>%
  select(-pue,-PUEsd,-minPUE,-maxPUE,-meanPUE,)


#Create a column for whether or not an observation falls above or below MAP 
legacydata<-legacydata%>%
  rename(MAP=PPTpixmean)%>%
   mutate(above_below = case_when(
     (PPT>MAP)~"above",
     (PPT<MAP)~"below"))

#Create fracHERB column for later use 
legacydata$herbaceousNPP<-legacydata$afgNPP+legacydata$pfgNPP
legacydata$fracHERB<-legacydata$herbaceousNPP/legacydata$NPP

write_rds(legacydata,"legacydata.rds")


```
